## Sparse Arrays in julia

References:
-  [Sparse Arrays](https://docs.julialang.org/en/v1.4/stdlib/SparseArrays/)

### Compressed Sparse Column (CSC) Sparse Matrix Storage

In [1]:
using SparseArrays
using Printf

In [2]:
A = sparse([1, 1, 2, 3], [1, 3, 2, 3], [0, 1, 2, 0])

3×3 SparseMatrixCSC{Int64,Int64} with 4 stored entries:
  [1, 1]  =  0
  [2, 2]  =  2
  [1, 3]  =  1
  [3, 3]  =  0

In [3]:
dropzeros(A)

3×3 SparseMatrixCSC{Int64,Int64} with 2 stored entries:
  [2, 2]  =  2
  [1, 3]  =  1

### Sparse Vector and Matrix Constructors

In [7]:
spzeros(3)

3-element SparseVector{Float64,Int64} with 0 stored entries

In [41]:
spzeros(3,3)

3×3 SparseMatrixCSC{Float64,Int64} with 0 stored entries

In [8]:
 I = [1, 4, 3, 5]; J = [4, 7, 18, 9]; V = [1, 2, -5, 3];

In [10]:
# sparse(I,J,V) then constructs a sparse matrix such that 
# S[I[k], J[k]] = V[k]
S = sparse(I,J,V)

5×18 SparseMatrixCSC{Int64,Int64} with 4 stored entries:
  [1,  4]  =  1
  [4,  7]  =  2
  [5,  9]  =  3
  [3, 18]  =  -5

In [55]:
# The inverse of the sparse and sparsevec functions 
# is findnz, which retrieves the inputs used to 
# create the sparse array
B = findnz(S)

([1, 4, 5, 3], [4, 7, 9, 18], [1, 2, 3, -5])

In [59]:
println(typeof(B))
println(B[1])
println(B[2])
println(B[3])

Tuple{Array{Int64,1},Array{Int64,1},Array{Int64,1}}
[1, 4, 5, 3]
[4, 7, 9, 18]
[1, 2, 3, -5]


In [12]:
findall(!iszero, S)

4-element Array{CartesianIndex{2},1}:
 CartesianIndex(1, 4)
 CartesianIndex(4, 7)
 CartesianIndex(5, 9)
 CartesianIndex(3, 18)

Another way to create a sparse array is to convert a dense array into a sparse array using the sparse function:

In [88]:
A = [1 0; 0 0]
B = repeat(A, 2, 3)

4×6 Array{Int64,2}:
 1  0  1  0  1  0
 0  0  0  0  0  0
 1  0  1  0  1  0
 0  0  0  0  0  0

#### To Sparse and To dense view:

In [95]:
S = sparse(B)
@show S
Array(S)

S = 
  [1, 1]  =  1
  [3, 1]  =  1
  [1, 3]  =  1
  [3, 3]  =  1
  [1, 5]  =  1
  [3, 5]  =  1


4×6 Array{Int64,2}:
 1  0  1  0  1  0
 0  0  0  0  0  0
 1  0  1  0  1  0
 0  0  0  0  0  0

In [22]:
sparse([1.0, 0.0, 1.0])

3-element SparseVector{Float64,Int64} with 2 stored entries:
  [1]  =  1.0
  [3]  =  1.0

The issparse function can be used to query if a matrix is sparse.

In [23]:
issparse(spzeros(5))

true

Indexing operations, especially assignment, are expensive, when carried out one element at a time. In many cases it may be better to convert the sparse matrix into `(I,J,V)` format using `findnz`, manipulate the values or the structure in the dense vectors `(I,J,V)`, and then reconstruct the sparse matrix.

In [39]:
# Creates a m-by-n random matrix (of density d)
sprand(3, 3, 0.3) 

3×3 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [2, 1]  =  0.405025
  [2, 3]  =  0.93208
  [3, 3]  =  0.33711

In [44]:
sprand(Bool, 3, 4, 0.5)

3×4 SparseMatrixCSC{Bool,Int64} with 4 stored entries:
  [2, 1]  =  1
  [3, 1]  =  1
  [3, 2]  =  1
  [1, 4]  =  1

In [46]:
sprand(Float64, 5, 0.5)

5-element SparseVector{Float64,Int64} with 3 stored entries:
  [1]  =  0.185637
  [2]  =  0.786457
  [4]  =  0.555272

In [47]:
sprandn(2, 2, 0.75)

2×2 SparseMatrixCSC{Float64,Int64} with 3 stored entries:
  [1, 1]  =  -0.508226
  [2, 1]  =  2.19075
  [2, 2]  =  0.348588

In [48]:
A = sparse([1, 0, 1])
nonzeros(A)

2-element Array{Int64,1}:
 1
 1

[nzrange](https://docs.julialang.org/en/v1.4/stdlib/SparseArrays/#SparseArrays.nzrange)

In [54]:
I = [1, 4, 3, 5]; J = [4, 7, 18, 9]; V = [1, 2, -5, 3];
A = sparse(I,J,V)
rows = rowvals(A)
vals = nonzeros(A)
m, n = size(A)
@show A;
for j = 1:n
   for i in nzrange(A, j)
      row = rows[i]
      val = vals[i]
      # perform sparse wizardry...
   end
end

A = 
  [1,  4]  =  1
  [4,  7]  =  2
  [5,  9]  =  3
  [3, 18]  =  -5


In [4]:
I = [1, 4, 3, 5]; J = [4, 7, 18, 9]; V = [1, 2, -5, 3];
A = sparse(I,J,V)
println(size(A))
println("nonzeros : ", nonzeros(A))
println("rowvals : ", rowvals(A))

rows = rowvals(A)
vals = nonzeros(A)

row, col = size(A)
println("row, col :", row, " ", col)
for j = 1: col
    for i in nzrange(A, j)
        @printf("row = %3d, col = %3d, val = %3d \n", rows[i], j, vals[i])
    end
end

println(typeof(Array(A)))
Array(A)

(5, 18)
nonzeros : [1, 2, 3, -5]
rowvals : [1, 4, 5, 3]
row, col :5 18
row =   1, col =   4, val =   1 
row =   4, col =   7, val =   2 
row =   5, col =   9, val =   3 
row =   3, col =  18, val =  -5 
Array{Int64,2}


5×18 Array{Int64,2}:
 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0   0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0   0
 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  -5
 0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0   0
 0  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0   0

In [7]:
I = [1, 4, 3, 5]; J = [4, 7, 18, 9]; V = [1, 2, -5, 3];
A = sparse(I,J,V)
println("nonzeros : ", nonzeros(A))
println("rowvals : ", rowvals(A))
rows = rowvals(A)
vals = nonzeros(A)
row, col = size(A)
for j = 1: col
    @printf("col = %3d, ", j)
    for i in nzrange(A, j)
        @printf("i = %3d, row = %3d", i, rows[i])
    end
    @printf("\n")
end

nonzeros : [1, 2, 3, -5]
rowvals : [1, 4, 5, 3]
col =   1, 
col =   2, 
col =   3, 
col =   4, i =   1, row =   1
col =   5, 
col =   6, 
col =   7, i =   2, row =   4
col =   8, 
col =   9, i =   3, row =   5
col =  10, 
col =  11, 
col =  12, 
col =  13, 
col =  14, 
col =  15, 
col =  16, 
col =  17, 
col =  18, i =   4, row =   3


In [9]:
I = [1, 4, 3, 5]; J = [4, 7, 18, 9]; V = [1, 2, -5, 3];
A = sparse(I,J,V)

for i = 1:length(I)
    @printf("row = %3d, col = %3d, val = %3d \n", I[i], J[i], V[i])
end

row =   1, col =   4, val =   1 
row =   4, col =   7, val =   2 
row =   3, col =  18, val =  -5 
row =   5, col =   9, val =   3 
