### Arrays 
- References
    - [Julia by example](https://juliabyexample.helpmanual.io/)
    - [Multi-dimensional Arrays](https://docs.julialang.org/en/v1/manual/arrays/)

In [1]:
function printsum(a)
    # summary generates a summary of an object
    println(summary(a), ": ", repr(a))
end

printsum (generic function with 1 method)

In [4]:
a1 = [1,2,3]
printsum(a1)

3-element Array{Int64,1}: [1, 2, 3]


In [5]:
a2 = []
printsum(a2)

0-element Array{Any,1}: Any[]


In [7]:
# since this array has no type, functions like push! (see below) don't work
# instead arrays can be initialised with a type:
a3 = Int64[]
printsum(a3)

0-element Array{Int64,1}: Int64[]


In [8]:
# ranges are different from arrays:
a4 = 1:20
printsum(a4)

20-element UnitRange{Int64}: 1:20


In [9]:
# however they can be used to create arrays thus:
a4 = collect(1:20)
printsum(a4)

20-element Array{Int64,1}: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [10]:
# arrays can also be generated from comprehensions:
a5 = [2^i for i = 1:10]
printsum(a5)

10-element Array{Int64,1}: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]


In [11]:
# arrays can be any type, so arrays of arrays can be created:
a6 = (Array{Int64, 1})[]
printsum(a6)

0-element Array{Array{Int64,1},1}: Array{Int64,1}[]


In [21]:
# Julia provided a number of "Dequeue" functions, the most common
# for appending to the end of arrays is push!
# ! at the end of a function name indicates that 
# the first argument is updated.
a1 = [1,2,3]
push!(a1, 4)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [24]:
# using repeat() to create arrays
# you must use the keywords "inner" and "outer"
# all arguments must be arrays (not ranges)
a1 = [1,2,3]
a7 = repeat(a1,inner=[2],outer=[1])
printsum(a7)

6-element Array{Int64,1}: [1, 1, 2, 2, 3, 3]


In [25]:
a8 = repeat(collect(4:-1:1),inner=[1],outer=[2])
printsum(a8)

8-element Array{Int64,1}: [4, 3, 2, 1, 4, 3, 2, 1]


### [Multidimensional Arrays](https://docs.julialang.org/en/v1/base/arrays/)

In [27]:
zeros(Int8, 2, 3)

2×3 Array{Int8,2}:
 0  0  0
 0  0  0

In [28]:
zeros(Int8, (2, 3))

2×3 Array{Int8,2}:
 0  0  0
 0  0  0

In [29]:
zeros((2, 3))

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [34]:
[[1, 2, 3],[4.0, 5.0]]

2-element Array{Array{Float64,1},1}:
 [1.0, 2.0, 3.0]
 [4.0, 5.0]

In [ ]:
# Core.Array
# Array{T}(undef, dims)
# Array{T,N}(undef, dims)

In [23]:
A = Array{Float64,2}(undef, 2, 3) # N given explicitly

2×3 Array{Float64,2}:
 6.01347e-154  6.01347e-154  6.89906e-310
 6.01347e-154  6.01347e-154  6.92734e-310

In [24]:
B = Array{Float64}(undef, 2) # N determined by the input

2-element Array{Float64,1}:
 6.9273140954847e-310
 6.92733635362664e-310

In [ ]:
# Array{T}(nothing, dims)
# Array{T,N}(nothing, dims)

In [25]:
Array{Union{Nothing, String}}(nothing, 2)

2-element Array{Union{Nothing, String},1}:
 nothing
 nothing

In [26]:
Array{Union{Nothing, Int}}(nothing, 2, 3)

2×3 Array{Union{Nothing, Int64},2}:
 nothing  nothing  nothing
 nothing  nothing  nothing

In [27]:
Array{Float64,1}(UndefInitializer(), 3)

3-element Array{Float64,1}:
 6.9273126747606e-310
 6.9273126747622e-310
 6.92729520762226e-310

In [28]:
Array{Float64,1}(undef, 3)

3-element Array{Float64,1}:
 6.9273448606434e-310
 6.9273404775515e-310
 6.92734047842894e-310

In [30]:
# Base.Vector
# Vector{T}(undef, n)
Vector{Float64}(undef, 3)

3-element Array{Float64,1}:
 6.92734047842894e-310
 6.9273126813534e-310
 6.9273404775515e-310

In [33]:
# Base.Matrix
# Matrix{T}(undef, m, n)
Matrix{Float64}(undef, 2, 3)

2×3 Array{Float64,2}:
 6.92734e-310  6.92731e-310  6.92731e-310
 6.92731e-310  6.92731e-310  6.92734e-310

In [37]:
# Base.fill
# Base.fill!
A = fill(1, (5,5))

5×5 Array{Int64,2}:
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1

In [38]:
A = zeros(2,3)

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [43]:
# fill!(A, 2.0)
A

2×3 Array{Float64,2}:
 2.0  2.0  2.0
 2.0  2.0  2.0

Fill array `A` with the value `x`. If x is an object reference, all elements will refer to the same object. `fill!(A, Foo())` will return A filled with the result of evaluating `Foo()` once.

In [49]:
a = [1, 1, 1, 1]
A = fill!(Vector{Vector{Int}}(undef, 3), a)
a[1] = 2 
A

3-element Array{Array{Int64,1},1}:
 [2, 1, 1, 1]
 [2, 1, 1, 1]
 [2, 1, 1, 1]

### Concatenation

If the arguments inside the square brackets are separated by semicolons (;) or newlines instead of commas, then their contents are vertically concatenated together instead of the arguments being used as elements themselves.

In [35]:
[1:2, 4:5]

2-element Array{UnitRange{Int64},1}:
 1:2
 4:5

In [36]:
[1:2; 4:5]

4-element Array{Int64,1}:
 1
 2
 4
 5

In [37]:
[1:2
 4:5
 6]

5-element Array{Int64,1}:
 1
 2
 4
 5
 6

In [38]:
[1:2 4:5 6:7]

2×3 Array{Int64,2}:
 1  4  6
 2  5  7

In [39]:
[[1,2]  [4,5]  [7,8]]

2×3 Array{Int64,2}:
 1  4  7
 2  5  8

In [40]:
[1 2 3] # Numbers can also be horizontally concatenated

1×3 Array{Int64,2}:
 1  2  3

Using semicolons (or newlines) and spaces (or tabs) can be combined to concatenate both horizontally and vertically at the same time.

In [41]:
[1 2
 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [42]:
[zeros(Int, 2, 2) [1; 2]
        [3 4] 5]

3×3 Array{Int64,2}:
 0  0  1
 0  0  2
 3  4  5

In [43]:
[[1 2] [3 4]]

1×4 Array{Int64,2}:
 1  2  3  4

In [44]:
Int8[[1 2] [3 4]]

1×4 Array{Int8,2}:
 1  2  3  4

### Comprehensions

In [46]:
[Float64(i) for i=1:10]

10-element Array{Float64,1}:
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

### Generator Expressions

In [48]:
(Float64(i) for i=1:10)

Base.Generator{UnitRange{Int64},Type{Float64}}(Float64, 1:10)

In [49]:
sum(1/n^2 for n=1:1000)

1.6439345666815615

In [50]:
[(i,j) for i=1:3 for j=1:i]

6-element Array{Tuple{Int64,Int64},1}:
 (1, 1)
 (2, 1)
 (2, 2)
 (3, 1)
 (3, 2)
 (3, 3)

**Arrays are column wise in julia**

In [51]:
A = reshape(collect(1:16), (4, 4))

4×4 Array{Int64,2}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [52]:
x = reshape(1:16, 4, 4)

4×4 reshape(::UnitRange{Int64}, 4, 4) with eltype Int64:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [53]:
x[2:3, 2:end-1]

2×2 Array{Int64,2}:
 6  10
 7  11

In [55]:
x[[2, 5, 8]]

3-element Array{Int64,1}:
 2
 5
 8

In [57]:
x[2,:]

4-element Array{Int64,1}:
  2
  6
 10
 14

In [58]:
x[:, 3]

4-element Array{Int64,1}:
  9
 10
 11
 12

In [1]:
A = cat([1 2; 3 4], [5 6; 7 8], dims=3)

2×2×2 Array{Int64,3}:
[:, :, 1] =
 1  2
 3  4

[:, :, 2] =
 5  6
 7  8

### Arrays of Arrays

In [69]:
A = [[1,2,3], [4,5,6]]

2-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5, 6]

In [70]:
println(A[1])
println(A[1][3])
println(A[1][1:2])
println(A[1:2])

[1, 2, 3]
3
[1, 2]
[[1, 2, 3], [4, 5, 6]]


In [71]:
hcat(A...)

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [72]:
vcat(A...)

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [68]:
a = Vector{Int}[[1,2,5], [3,4]]

2-element Array{Array{Int64,1},1}:
 [1, 2, 5]
 [3, 4]

In [55]:
print(a[1], " ", a[1][1], " ", a[1][2])

[1, 2] 1 2

In [59]:
A = Array{Float64,2}(undef, 3, 3)  # A single Array, dimensions 3 by 3, of Float64 type objects

3×3 Array{Float64,2}:
 6.92731e-310  6.92731e-310  6.92731e-310
 6.92731e-310  6.92731e-310  6.92731e-310
 6.92731e-310  6.92731e-310  6.92731e-310

### Append

In [38]:
a = Array{Int64}[]
println(typeof(a))
for i = 1:3
    push!(a, [i*2, i*3])
end
a

Array{Array{Int64,N} where N,1}


3-element Array{Array{Int64,N} where N,1}:
 [2, 3]
 [4, 6]
 [6, 9]

In [39]:
b = hcat(a...)'

3×2 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 2  3
 4  6
 6  9

In [59]:
a = Array{Int64}[]
b = [1,2,3]
push!(b, 4)
println(typeof(a))
println(typeof(b))
push!(a, b)

c = [2, 4, 6]
push!(a, c)

Array{Array{Int64,N} where N,1}
Array{Int64,1}


2-element Array{Array{Int64,N} where N,1}:
 [1, 2, 3, 4]
 [2, 4, 6]